apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudsqlproxy-crmgwdata-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudsqlproxy
    spec:
      containers:
       # Make sure to specify image tag in production
       # Check out the newest version in release page
       # https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
      - image: b.gcr.io/cloudsql-docker/gce-proxy:latest
       # 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
        imagePullPolicy: Always
        name: cloudsqlproxy
        command:
        - /cloud_sql_proxy
        - -dir=/$HOME/Kubernetes
        - -instances=para-dev:us-central1:crmgwdata=tcp:0.0.0.0:3306
        - -credential_file=/$HOME/Kubernetes/security/Para-Dev_sqldev-db57e57e43bb.json
        ports:
        - name: port-crmgwdata
          containerPort: 3306
        volumeMounts:
        - mountPath: /cloudsql
          name: cloudsql
        - mountPath: /$HOME/Kubernetes/security
          name: sqldev
      volumes:
      - name: cloudsql
        emptyDir:
      - name: sqldev
        secret:
          secretName: sqldev
