

apiVersion: v1
kind: Service
metadata:
  name: crmgw-proxy
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: crmgw-proxy
    port: 8000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP
  - name: crmgw-proxy-ssl
    port: 8443
    targetPort: 8443
    nodePort: 30443
    protocol: TCP
  selector:
    app: crmgw

---
apiVersion: v1
kind: Service
metadata:
  name: crmgw-admin
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: crmgw-admin
    port: 8001
    targetPort: 8001
    nodePort: 30001
    protocol: TCP
  - name: crmgw-admin-ssl
    port: 8444
    targetPort: 8444
    nodePort: 30444
    protocol: TCP
  selector:
    app: crmgw

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crmgw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: crmgw
        app: crmgw
    spec:
      containers:
      - name: kong
        image: us.gcr.io/para-dev/gfkong:0.8
        env:
          - name: POSTGRES_USER
            value: kong
          - name: POSTGRES_PASSWORD
            value: kong
          - name: POSTGRES_NAME
            value: crmgwdata
          - name: POSTGRES_PORT
            value: "3306"

#-------------------------------------------------------------------------
#	For this parameter, here are some valid values
#
#            value: 107.178.222.38
#            value: sqlproxy-service-crmgwdata-dev
#            value: para-dev:us-central1:crmgwdata=tcp:0.0.0.0:3306
#-------------------------------------------------------------------------
          - name: POSTGRES_HOSTNAME
            value: sqlproxy-service-crmgwdata-dev


#-------------------------------------------------------------------------
#	For this parameter, here are some valid values
#
#           "KONG_CLUSTER_ADVERTISE=YOUR_HOST_IP_ADDR:7946" \
#	    "KONG_CLUSTER_LISTEN=YOUR_DOCKER_CONTAINER_INTERNAL_IP_ADDR:7946" \
#
#            value: 35.184.90.216:7946
#                fieldPath: status.podIP
#        command: [ "/bin/sh", "-c", "KONG_CLUSTER_ADVERTISE=$(KONG_HOST_IP):7946 KONG_NGINX_DAEMON='off' kong start && env" ]
#-------------------------------------------------------------------------
#          - name: KONG_CLUSTER_ADVERTISE
#            value: 35.184.90.216:7946
#          - name: KONG_CLUSTER_LISTEN
#            value: 10.23.249.138:7946

        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP




