
apiVersion: v1
kind: Service
metadata:
  name: crmgw-proxy-dns
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: crmgw-proxy
    port: 8000
    targetPort: 8000
    nodePort: 30005
    protocol: TCP
  - name: crmgw-proxy-ssl
    port: 8443
    targetPort: 8443
    nodePort: 30448
    protocol: TCP
  selector:
    app: crmgw-dns

---
apiVersion: v1
kind: Service
metadata:
  name: crmgw-admin-dns
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: crmgw-admin
    port: 8001
    targetPort: 8001
    nodePort: 30006
    protocol: TCP
  - name: crmgw-admin-ssl
    port: 8444
    targetPort: 8444
    nodePort: 30449
    protocol: TCP
  selector:
    app: crmgw-dns

